---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: niri-dank
description: Fedora Atomic with Niri + Dank Linux Shell

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - atim/starship
        - yalter/niri
        - avengemedia/dms
        - alternateved/keyd
    install:
      packages:
        - niri
        - dms
        - distrobox
        - toolbox
        - neovim
        - emacs
        - wl-clipboard
        - pavucontrol
        - git
        - starship
        - kitty
        - zsh
        - tailscale
        - keyd   # Used to map Capslock to Hyperkey (Ctrl+Alt+Shift+Meta)
        - yubikey-manager
        - yubikey-manager-qt
        - chsh
        - gnupg2-scdaemon
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: brew
    nofile-limits: true
    brew-analytics: false
  
  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - keyd.service
        - tailscaled.service
  #  user:
  #    enabled:
  #      - niri-session.target
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
